services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\InpostBundle\ConfigProvider: ~
    Answear\InpostBundle\Client: ~

    Answear\InpostBundle\:
        resource: '../../../src/{Command,Client}'

